version: "2"

linters:
  settings:
    revive:
      rules:
        - name: var-naming
          arguments:
            - ["ID"]
            - ["VM"]
            - ["API"]
  default: standard
  enable:
    - errorlint
    - misspell
    - nilerr
    - revive

formatters:
  enable:
    - gofmt
    - goimports